

CREATE db IF NOT EXISTS Rocket (TestID INTEGER(3) NOT NULL AUTO_INCREMENT, Title VARCHAR(10) NOT NULL,
About VARCHAR(500) NOT NULL, Image MEDIUMBLOB PRIMARY KEY(TesttID));

CREATE TABLE IF NOT EXISTS notebook.test (TestID INTEGER(3) NOT NULL AUTO_INCREMENT, Title VARCHAR(10) NOT NULL,
About VARCHAR(500) NOT NULL, Image MEDIUMBLOB PRIMARY KEY(TesttID));